WebApplication3/Controllers/CategoryUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;
using System.Data.Entity;
using System.Net;

namespace WebApplication3.Controllers
{
    public class CategoryUserController : Controller
    {
        pjt3hEntities db = new pjt3hEntities();
        [HttpGet]
        // GET: CategoryUser
        public ActionResult Index(int? id)
        {
            if(id.HasValue)
            {
                return View(db.Products.Where(c=>c.categoryid==id).ToList());
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }
        public PartialViewResult MenuCategories()
        {
            
            return PartialView(db.Categories.ToList());
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }

            return View(category);
        }
    }
}

WebApplication3/Views/CategoryUser/Details.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

WebApplication3/Views/CategoryUser/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@using WebApplication3.Models;
@model List<Product> 
@{pjt3hEntities db = new pjt3hEntities(); }
<h2 class="title text-center">Danh sách sản phẩm</h2>
@foreach (var item in Model)
{
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="@item.image" alt="" width="150" height="268" onclick="location.href='@Url.Action("Details","CategoryUser",new { id=@item.id})'"/>
                    <h2>Giá: @string.Format("{0:0,0}", item.price)</h2>
                    <p>@item.name @*(@item.quantity)*@</p>
                    <a href="/Cart/ThemVaoGioHang/@item.id" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                </div>
                @*<div class="product-overlay">
                        <div class="overlay-content">
                            <h2>Giá: @item.Price</h2>
                            <p>@item.ProductName</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                        </div>
                    </div>*@
            </div>
            <div class="choose">
                <ul class="nav nav-pills nav-justified">
                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                </ul>
            </div>
        </div>
    </div>
}

WebApplication3/Views/CategoryUser/MenuCategories.cshtml
@using WebApplication3.Models;
@model IEnumerable<Category>
    @{pjt3hEntities db=new pjt3hEntities();}

@foreach (var item in Model)
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title"><a href="@Url.Action("Index","CategoryUser",new { @id=item.id})"> <span class="pull-right ">(@db.Products.Where(c=>c.categoryid==item.id).Count())</span>@item.name</a></h4>
           
        </div>
    </div>
}