WebApplication3/Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> categoryid { get; set; }
        public Nullable<int> supplierid { get; set; }
        public string image { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string information { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
        public string description { get; set; }
        public Nullable<double> total { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}

WebApplication3/Controllers/ProductsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;
using System.IO;

namespace WebApplication3.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        pjt3hEntities db = new pjt3hEntities();

        public JsonResult GetAllProduct()
        {
            var product = db.Products.OrderByDescending(p => p.datecreate);
            return Json(from pro in product
                        select new
                        {
                            pro.id,
                            pro.name,
                            pro.image,
                            pro.price,
                            pro.quantity,
                            pro.information,
                            pro.datecreate,
                            pro.description
                        },JsonRequestBehavior.AllowGet);
        }
        // GET: Products
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Category).Include(p => p.Supplier);
            return View(products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            //ViewBag.authorid = new SelectList(db.Authors, "id", "name");
            ViewBag.categoryid = new SelectList(db.Categories, "id", "name");
            ViewBag.supplierid = new SelectList(db.Suppliers, "id", "name");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "id,name,categoryid,supplierid,image,price,quantity,information,datecreate,description")] Product product,HttpPostedFileBase upload)
        {
            Category category = db.Categories.SingleOrDefault(c=>c.id==product.categoryid);
            if (ModelState.IsValid)
            {
                if(upload != null && upload.ContentLength>0)
                {
                    string filename = Path.GetFileName(upload.FileName);
                    if (filename != null)
                    {
                        string path = Path.Combine(Server.MapPath("~/image"),filename);
                        upload.SaveAs(path);
                    }
                    product.image = "/image/" + filename;
                }
                else
                {
                    product.image = "/image/noproduct.PNG";
                }
                product.datecreate = DateTime.Now;
                if (category != null) category.status = "Còn hàng";
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.authorid = new SelectList(db.Authors, "id", "name", product.authorid);
            ViewBag.categoryid = new SelectList(db.Categories, "id", "name", product.categoryid);
            ViewBag.supplierid = new SelectList(db.Suppliers, "id", "name", product.supplierid);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            //ViewBag.authorid = new SelectList(db.Authors, "id", "name", product.authorid);
            ViewBag.categoryid = new SelectList(db.Categories, "id", "name", product.categoryid);
            ViewBag.supplierid = new SelectList(db.Suppliers, "id", "name", product.supplierid);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        
        public ActionResult Edit([Bind(Include = "id,name,categoryid,supplierid,image,price,quantity,information,datecreate,description")] Product product,HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                var currentProduct = db.Products.AsNoTracking().FirstOrDefault(p => p.id==(product.id));

                if (upload != null && upload.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(upload.FileName);
                    if (fileName != null)
                    {
                        string path = Path.Combine(Server.MapPath("~/image"), fileName);
                        upload.SaveAs(path);
                    }
                    product.image = "/image/" + fileName;
                }
                if(product.image == null || upload== null)
                {
                    if (currentProduct != null) product.image = currentProduct.image;
                }
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //ViewBag.authorid = new SelectList(db.Authors, "id", "name", product.authorid);
            ViewBag.categoryid = new SelectList(db.Categories, "id", "name", product.categoryid);
            ViewBag.supplierid = new SelectList(db.Suppliers, "id", "name", product.supplierid);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            if (product != null) db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication3/Views/Products/Create.cshtml
@model WebApplication3.Models.Product

@{
    ViewBag.Title = "Create"; Layout = "~/Views/Shared/_LayoutPageADM.cshtml";
}

<h2>Create</h2>
@*<script src="~/Scripts/jquery.validate.min.js"></script>*@
<script src="~/Scripts/ckeditor/ckeditor.js"></script>
@using (Html.BeginForm("Create", "Products", null, FormMethod.Post, new { @enctype = "Multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoryid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("categoryid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.categoryid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.supplierid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("supplierid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.supplierid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="~/image/NoProduct.png" class="img-responsive img-thumbnail" id="image_edit" />
                <input type="file" id="image" name="upload" onchange="readURL(this);"/>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.information, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.information, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.information, "", new { @class = "text-danger" })
                <script>CKEDITOR.replace("information");</script>
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                <script>
                    CKEDITOR.replace("description");
                </script>
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-4 col-md-8">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <button class="btn btn-success" onclick="location.href='@Url.Action("Index","Products")'">Quay trở lại</button>
</div>

WebApplication3/Views/Products/Delete.cshtml
@model WebApplication3.Models.Product

@{
    ViewBag.Title = "Delete"; Layout = "~/Views/Shared/_LayoutPageADM.cshtml";
}

<h2>Xóa</h2>

<h3>Bạn có chắc chắn muốn xóa điều này?</h3>
<div>
    <h4>Sản phẩm</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            <img src="@Model.image" width="150"/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.information)
        </dt>

        <dd>
            @Html.Raw(Model.information)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datecreate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datecreate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.Raw(Model.description)
        </dd>

        

        <dt>
            @Html.DisplayNameFor(model => model.Category.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supplier.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supplier.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Chấp nhận" class="btn btn-danger" /> |
            <button class="btn btn-info" onclick="location.href='@Url.Action("Edit","Products")'">Quay trở lại</button>
        </div>
    }
</div>

WebApplication3/Views/Products/Details.cshtml
@model WebApplication3.Models.Product

@{
    ViewBag.Title = "Details"; Layout = "~/Views/Shared/_LayoutPageADM.cshtml";
}

<h2>Chi tiết</h2>

<div>
    <h4>Sản phấm</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            <img src="@Model.image" width="150" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor( model=>model.information)
        </dt>

        <dd>
            @Html.Raw(Model.information)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datecreate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datecreate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model=>model.description)
        </dt>

        <dd>
            @Html.Raw(Model.description)
        </dd>

        

        <dt>
            @Html.DisplayNameFor(model => model.Category.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supplier.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Supplier.name)
        </dd>

    </dl>
</div>
<p>
    <button class="btn btn-success" onclick="location.href='@Url.Action("Edit","Products",new { id=Model.id})'">Sửa sản phẩm</button> |
    <button class="btn btn-info" onclick="location.href='@Url.Action("Index","Products")'">Quay trở lại</button>
</p>

WebApplication3/Views/Products/Edit.cshtml
@model WebApplication3.Models.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPageADM.cshtml";
}

<h2>Sửa</h2>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/ckeditor/ckeditor.js"></script>
@using (Html.BeginForm(Html.BeginForm("Edit", "Products", null, FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sản phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoryid, "categoryid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("categoryid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.categoryid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.supplierid, "supplierid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("supplierid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.supplierid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Model.image" class="img-responsive img-thumbnail" id="image_edit"/>
                <input type="file" name="upload" id="image" value="@Model.image" onchange="readURL(this);"/>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.information, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.information, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.information, "", new { @class = "text-danger" })
                <script>
                    CKEDITOR.replace("information");
                </script>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.datecreate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.datecreate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.datecreate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                <script>
                    CKEDITOR.replace("description");
                </script>
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu thay đổi" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <button class="btn btn-info" onclick="location.href='@Url.Action("Index","Products")'">Quay trở lại</button>
</div>

WebApplication3/Views/Products/Index.cshtml
@model IEnumerable<WebApplication3.Models.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPageADM.cshtml";
}

<h2>Index</h2>

<p>
    <button class="btn btn-primary" onclick="location.href='@Url.Action("Create","Products")'">Tạo mới</button>
</p>


<div class="form-horizontal">
    <table class="table table-bordered table-responsive" id="product">
        <thead>
            <tr>
                <th>
                    Tên sản phẩm
                </th>
                <th>
                    Ảnh
                </th>
                <th>
                    Giá
                </th>
                <th>
                    Số lượng
                </th>
                <th>
                    Thông tin sản phẩm
                </th>

                <th>
                    Mô tả sản phẩm
                </th>
                <th width="100">Thao tác</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
@section Scripts{ 
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<link href="~/Content/jquery.dataTables.min.css" rel="stylesheet" />
<script src="~/Content/jquery.dataTables.min.js"></script>
@*<script src="~/Scripts/dataTables.bootstrap.min.js"></script>*@
<script type="text/javascript">
    $(document).ready(
        function () {
        $.getJSON('@Url.Action("GetAllProduct","Products")', function (data) {
                var tr;
                for (var i = 0; i < data.length; i++) {
                    tr = $('<tr/>');
                    tr.append("<td>" + data[i].name + "</td>");
                    tr.append("<td><img src='" + data[i].image + "' width='150'></td>");
                    tr.append("<td>" + data[i].price + "</td>");
                    tr.append("<td>" + data[i].quantity + "</td>");
                    tr.append("<td>" + data[i].information + "</td>");
                    tr.append("<td>" + data[i].description + "</td>");
                    tr.append("<td><a class='btn btn-success btn-sm fa fa-pencil fa-lg' href='Products/Edit/" +
                        data[i].id + "'></a> <a class='btn btn-info btn-sm fa fa-asterisk' href='Products/Details/" +
                        data[i].id + "'></a>  <a class='btn btn-danger btn-sm fa fa-trash-o fa-lg' href='Products/Delete/" +
                        data[i].id + "'></a></td>");
                    $('table').append(tr);
                }
                $('#product').DataTable();
            });
        });
    $(window).scroll(function () {
        var wScroll = $(this).scrollTop();
        var showScrollButton = 50;
        if (wScroll > showScrollButton) {
            $('#top').fadeIn();
        }
        else {
            $('#top').fadeOut();
        }
    });
    $('body').append('<a id="top" href="#"> <img src="/image/images.jpg" width="50px" height="150px"/> </a>');
    $('#top').css({
        "bottom": "0px",
        "right": "0px",
        "position": "fixed",
        "cursor": "pointer",
        "z-index": "1",
        "display": "none",
        "background-color": "rgba(0,0,0,0.7)",
        
        "corlor": "#ffffff"
    });
    $('#top').click(function () {
        $('body,html').animate(
            {
                scrollTop: 0
            }, 500);
        return false;
    });
</script>
}